### ISSUE TITLE
Option to default to today's date

### ISSUE THREAD

**Issue by jrmullaney** [lsst-sqre/times-square#77]
If one is using Times SQuaRE to check nightly processing, it would be really useful if there was some way to get the date to default to today's date.

I was thinking along the lines of the developer being able to have something along the lines of:
```
parameters:
  day_obs:
    type: string
    description: Observation Night (YYYY-MM-DD)
    default: "{today}"
```
should they want to default to today's date. I guess the format of the returned value may have to be fixed, with any necessary re-formatting happening in the notebook.
